version: '3.4'

services:
  api:
    container_name: studybuddy-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__StudyBuddyDbContext=Host=db;Port=5432;Username=postgres;Password=postgres;Database=studybuddydb;
      - JwtOptions__SecretKey=secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
      - JwtOptions__ExpiresHours=52
    ports:
      - "8080:80"  # Порты для API
      - "8081:443"
    depends_on:
      - db
    volumes:
      - ./StudyBuddy.API/appsettings.json:/app/appsettings.json  # Монтирование файла конфигурации
    networks:
      - studybuddy_network

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: studybuddydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Прокси порт для PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - studybuddy_network

volumes:
  postgres-data:

networks:
  studybuddy_network:
    driver: bridge
